import ContextProvider from "@/components/context/ContextProvider";
import type { Metadata } from "next";
import { DM_Sans, Bricolage_Grotesque } from "next/font/google";
import "../../public/assets/css/style.css";
import "swiper/css";
import "swiper/css/navigation";
import 'swiper/css/pagination'; 
import CustomLayout from "@/components/layout/CustomLayout";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* ✅ Use both fonts in the body */}
      <body className={`${dmSans.variable} ${bricolage.variable}`}>
        <ContextProvider>
          <CustomLayout>
            {children}
          </CustomLayout>
        </ContextProvider>
      </body>
    </html>
  );
}
